# 运行环境
spring:
  profiles:
    active: dev
  # 数据源配置
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456